### PR TITLE
fix install+config title

### PR DESCRIPTION
**Pull request by susanev**
hi! we are doing some seo cleanup over in the registry, and w are updating the titles to align with those changes. this will also allow us to support breadcrumbs on the page.

after merging this requires a release for the registry to know about it. thank you!!

### CODE REVIEW

**Comment by astipkovits** [comment]
Hello @susanev, Do I understand correctly, that I need to release a new minor version in my repository for the pulumi registry to pick it up? This is my understanding, but wanted to double check.

**Comment by susanev** [comment]
thats correct, thank you!!

**Comment by astipkovits** [comment]
Thanks, will get this done soon

**Comment by astipkovits** [comment]
Merged and new minor version released.

**Pull request merged**
